[map[fk_ddl:ALTER TABLE public.ai_review_log ADD CONSTRAINT ai_review_log_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.authorized_persons ADD CONSTRAINT authorized_persons_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.authorized_persons ADD CONSTRAINT authorized_persons_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.builder_announcements ADD CONSTRAINT builder_announcements_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES builders(id);
ALTER TABLE public.builder_announcements ADD CONSTRAINT builder_announcements_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES profiles(id);
ALTER TABLE public.builder_announcements ADD CONSTRAINT builder_announcements_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.builder_feature_packages ADD CONSTRAINT builder_feature_packages_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id);
ALTER TABLE public.builder_feature_packages ADD CONSTRAINT builder_feature_packages_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES builders(id) ON DELETE CASCADE;
ALTER TABLE public.builder_feature_packages ADD CONSTRAINT builder_feature_packages_package_id_fkey FOREIGN KEY (package_id) REFERENCES feature_packages(id) ON DELETE CASCADE;
ALTER TABLE public.builder_members ADD CONSTRAINT builder_members_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES builders(id) ON DELETE CASCADE;
ALTER TABLE public.builder_members ADD CONSTRAINT builder_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.builder_societies ADD CONSTRAINT builder_societies_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES builders(id) ON DELETE CASCADE;
ALTER TABLE public.builder_societies ADD CONSTRAINT builder_societies_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.bulletin_comments ADD CONSTRAINT bulletin_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.bulletin_comments ADD CONSTRAINT bulletin_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES bulletin_posts(id) ON DELETE CASCADE;
ALTER TABLE public.bulletin_posts ADD CONSTRAINT bulletin_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.bulletin_posts ADD CONSTRAINT bulletin_posts_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.bulletin_rsvps ADD CONSTRAINT bulletin_rsvps_post_id_fkey FOREIGN KEY (post_id) REFERENCES bulletin_posts(id) ON DELETE CASCADE;
ALTER TABLE public.bulletin_votes ADD CONSTRAINT bulletin_votes_post_id_fkey FOREIGN KEY (post_id) REFERENCES bulletin_posts(id) ON DELETE CASCADE;
ALTER TABLE public.call_feedback ADD CONSTRAINT call_feedback_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.call_feedback ADD CONSTRAINT call_feedback_interaction_id_fkey FOREIGN KEY (interaction_id) REFERENCES seller_contact_interactions(id) ON DELETE CASCADE;
ALTER TABLE public.call_feedback ADD CONSTRAINT call_feedback_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES profiles(id);
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_target_society_id_fkey FOREIGN KEY (target_society_id) REFERENCES societies(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.category_config ADD CONSTRAINT category_config_parent_group_fkey FOREIGN KEY (parent_group) REFERENCES parent_groups(slug) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.collective_buy_participants ADD CONSTRAINT collective_buy_participants_request_id_fkey FOREIGN KEY (request_id) REFERENCES collective_buy_requests(id);
ALTER TABLE public.collective_buy_participants ADD CONSTRAINT collective_buy_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.collective_buy_requests ADD CONSTRAINT collective_buy_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.collective_buy_requests ADD CONSTRAINT collective_buy_requests_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.collective_escalations ADD CONSTRAINT collective_escalations_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.collective_escalations ADD CONSTRAINT collective_escalations_tower_id_fkey FOREIGN KEY (tower_id) REFERENCES project_towers(id);
ALTER TABLE public.construction_milestones ADD CONSTRAINT construction_milestones_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES profiles(id);
ALTER TABLE public.construction_milestones ADD CONSTRAINT construction_milestones_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.coupon_redemptions ADD CONSTRAINT coupon_redemptions_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE;
ALTER TABLE public.coupon_redemptions ADD CONSTRAINT coupon_redemptions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.coupons ADD CONSTRAINT coupons_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.coupons ADD CONSTRAINT coupons_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_addresses ADD CONSTRAINT delivery_addresses_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.delivery_addresses ADD CONSTRAINT delivery_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_assignments ADD CONSTRAINT delivery_assignments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.delivery_assignments ADD CONSTRAINT delivery_assignments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES delivery_partners(id);
ALTER TABLE public.delivery_assignments ADD CONSTRAINT delivery_assignments_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES delivery_partner_pool(id);
ALTER TABLE public.delivery_assignments ADD CONSTRAINT delivery_assignments_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.delivery_locations ADD CONSTRAINT delivery_locations_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES delivery_assignments(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_partner_pool ADD CONSTRAINT delivery_partner_pool_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.delivery_partners ADD CONSTRAINT delivery_partners_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.delivery_tracking_logs ADD CONSTRAINT delivery_tracking_logs_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES delivery_assignments(id);
ALTER TABLE public.device_tokens ADD CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.dispute_comments ADD CONSTRAINT dispute_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id);
ALTER TABLE public.dispute_comments ADD CONSTRAINT dispute_comments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES dispute_tickets(id) ON DELETE CASCADE;
ALTER TABLE public.dispute_tickets ADD CONSTRAINT dispute_tickets_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.dispute_tickets ADD CONSTRAINT dispute_tickets_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES profiles(id);
ALTER TABLE public.domestic_help_attendance ADD CONSTRAINT domestic_help_attendance_help_entry_id_fkey FOREIGN KEY (help_entry_id) REFERENCES domestic_help_entries(id) ON DELETE CASCADE;
ALTER TABLE public.domestic_help_attendance ADD CONSTRAINT domestic_help_attendance_marked_by_fkey FOREIGN KEY (marked_by) REFERENCES profiles(id);
ALTER TABLE public.domestic_help_attendance ADD CONSTRAINT domestic_help_attendance_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.domestic_help_entries ADD CONSTRAINT domestic_help_entries_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.domestic_help_entries ADD CONSTRAINT domestic_help_entries_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.emergency_broadcasts ADD CONSTRAINT emergency_broadcasts_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES profiles(id);
ALTER TABLE public.emergency_broadcasts ADD CONSTRAINT emergency_broadcasts_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.expense_flags ADD CONSTRAINT expense_flags_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES society_expenses(id) ON DELETE CASCADE;
ALTER TABLE public.expense_flags ADD CONSTRAINT expense_flags_flagged_by_fkey FOREIGN KEY (flagged_by) REFERENCES profiles(id);
ALTER TABLE public.expense_flags ADD CONSTRAINT expense_flags_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles(id);
ALTER TABLE public.expense_views ADD CONSTRAINT expense_views_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES society_expenses(id) ON DELETE CASCADE;
ALTER TABLE public.favorites ADD CONSTRAINT favorites_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.favorites ADD CONSTRAINT favorites_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.favorites ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.feature_package_items ADD CONSTRAINT feature_package_items_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES platform_features(id) ON DELETE CASCADE;
ALTER TABLE public.feature_package_items ADD CONSTRAINT feature_package_items_package_id_fkey FOREIGN KEY (package_id) REFERENCES feature_packages(id) ON DELETE CASCADE;
ALTER TABLE public.featured_items ADD CONSTRAINT featured_items_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE SET NULL;
ALTER TABLE public.gate_entries ADD CONSTRAINT gate_entries_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.gate_entries ADD CONSTRAINT gate_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.gate_entries ADD CONSTRAINT gate_entries_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES profiles(id);
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.help_requests ADD CONSTRAINT help_requests_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.help_responses ADD CONSTRAINT help_responses_request_id_fkey FOREIGN KEY (request_id) REFERENCES help_requests(id) ON DELETE CASCADE;
ALTER TABLE public.help_responses ADD CONSTRAINT help_responses_responder_id_fkey FOREIGN KEY (responder_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.inspection_checklists ADD CONSTRAINT inspection_checklists_builder_acknowledged_by_fkey FOREIGN KEY (builder_acknowledged_by) REFERENCES profiles(id);
ALTER TABLE public.inspection_checklists ADD CONSTRAINT inspection_checklists_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.inspection_checklists ADD CONSTRAINT inspection_checklists_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.inspection_checklists ADD CONSTRAINT inspection_checklists_tower_id_fkey FOREIGN KEY (tower_id) REFERENCES project_towers(id);
ALTER TABLE public.inspection_items ADD CONSTRAINT inspection_items_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES inspection_checklists(id) ON DELETE CASCADE;
ALTER TABLE public.job_tts_cache ADD CONSTRAINT job_tts_cache_job_id_fkey FOREIGN KEY (job_id) REFERENCES worker_job_requests(id);
ALTER TABLE public.maintenance_dues ADD CONSTRAINT maintenance_dues_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.maintenance_dues ADD CONSTRAINT maintenance_dues_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.manual_entry_requests ADD CONSTRAINT manual_entry_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id);
ALTER TABLE public.manual_entry_requests ADD CONSTRAINT manual_entry_requests_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.manual_entry_requests ADD CONSTRAINT manual_entry_requests_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_events ADD CONSTRAINT marketplace_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.milestone_reactions ADD CONSTRAINT milestone_reactions_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES construction_milestones(id) ON DELETE CASCADE;
ALTER TABLE public.milestone_reactions ADD CONSTRAINT milestone_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_buyer_society_id_fkey FOREIGN KEY (buyer_society_id) REFERENCES societies(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES coupons(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_delivery_address_id_fkey FOREIGN KEY (delivery_address_id) REFERENCES delivery_addresses(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD CONSTRAINT orders_seller_society_id_fkey FOREIGN KEY (seller_society_id) REFERENCES societies(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE SET NULL;
ALTER TABLE public.parcel_entries ADD CONSTRAINT parcel_entries_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.parcel_entries ADD CONSTRAINT parcel_entries_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.parking_slots ADD CONSTRAINT parking_slots_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id);
ALTER TABLE public.parking_slots ADD CONSTRAINT parking_slots_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.parking_slots ADD CONSTRAINT parking_slots_tower_id_fkey FOREIGN KEY (tower_id) REFERENCES project_towers(id);
ALTER TABLE public.parking_violations ADD CONSTRAINT parking_violations_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES profiles(id);
ALTER TABLE public.parking_violations ADD CONSTRAINT parking_violations_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles(id);
ALTER TABLE public.parking_violations ADD CONSTRAINT parking_violations_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES parking_slots(id);
ALTER TABLE public.parking_violations ADD CONSTRAINT parking_violations_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.payment_milestones ADD CONSTRAINT payment_milestones_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.payment_milestones ADD CONSTRAINT payment_milestones_linked_milestone_id_fkey FOREIGN KEY (linked_milestone_id) REFERENCES construction_milestones(id);
ALTER TABLE public.payment_milestones ADD CONSTRAINT payment_milestones_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.payment_milestones ADD CONSTRAINT payment_milestones_tower_id_fkey FOREIGN KEY (tower_id) REFERENCES project_towers(id);
ALTER TABLE public.payment_records ADD CONSTRAINT payment_records_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.payment_records ADD CONSTRAINT payment_records_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.payment_records ADD CONSTRAINT payment_records_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.payment_settlements ADD CONSTRAINT payment_settlements_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.payment_settlements ADD CONSTRAINT payment_settlements_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id);
ALTER TABLE public.phone_otp_verifications ADD CONSTRAINT phone_otp_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.price_history ADD CONSTRAINT price_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES profiles(id);
ALTER TABLE public.price_history ADD CONSTRAINT price_history_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.products ADD CONSTRAINT products_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD CONSTRAINT products_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES subcategories(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE SET NULL;
ALTER TABLE public.project_answers ADD CONSTRAINT project_answers_answered_by_fkey FOREIGN KEY (answered_by) REFERENCES profiles(id);
ALTER TABLE public.project_answers ADD CONSTRAINT project_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES project_questions(id) ON DELETE CASCADE;
ALTER TABLE public.project_documents ADD CONSTRAINT project_documents_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.project_documents ADD CONSTRAINT project_documents_tower_id_fkey FOREIGN KEY (tower_id) REFERENCES project_towers(id) ON DELETE SET NULL;
ALTER TABLE public.project_documents ADD CONSTRAINT project_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES profiles(id);
ALTER TABLE public.project_questions ADD CONSTRAINT project_questions_asked_by_fkey FOREIGN KEY (asked_by) REFERENCES profiles(id);
ALTER TABLE public.project_questions ADD CONSTRAINT project_questions_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.project_towers ADD CONSTRAINT project_towers_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.push_logs ADD CONSTRAINT push_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.reports ADD CONSTRAINT reports_reported_seller_id_fkey FOREIGN KEY (reported_seller_id) REFERENCES seller_profiles(id);
ALTER TABLE public.reports ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES profiles(id);
ALTER TABLE public.resident_payments ADD CONSTRAINT resident_payments_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES payment_milestones(id);
ALTER TABLE public.resident_payments ADD CONSTRAINT resident_payments_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.resident_payments ADD CONSTRAINT resident_payments_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.search_demand_log ADD CONSTRAINT search_demand_log_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.security_staff ADD CONSTRAINT security_staff_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.security_staff ADD CONSTRAINT security_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_contact_interactions ADD CONSTRAINT seller_contact_interactions_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_contact_interactions ADD CONSTRAINT seller_contact_interactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.seller_contact_interactions ADD CONSTRAINT seller_contact_interactions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_conversation_messages ADD CONSTRAINT seller_conversation_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES seller_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.seller_conversation_messages ADD CONSTRAINT seller_conversation_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_conversations ADD CONSTRAINT seller_conversations_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_conversations ADD CONSTRAINT seller_conversations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.seller_conversations ADD CONSTRAINT seller_conversations_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_form_configs ADD CONSTRAINT seller_form_configs_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id);
ALTER TABLE public.seller_licenses ADD CONSTRAINT seller_licenses_group_id_fkey FOREIGN KEY (group_id) REFERENCES parent_groups(id) ON DELETE CASCADE;
ALTER TABLE public.seller_licenses ADD CONSTRAINT seller_licenses_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_profiles ADD CONSTRAINT seller_profiles_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE SET NULL;
ALTER TABLE public.seller_profiles ADD CONSTRAINT seller_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_recommendations ADD CONSTRAINT seller_recommendations_recommender_id_fkey FOREIGN KEY (recommender_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_recommendations ADD CONSTRAINT seller_recommendations_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.seller_recommendations ADD CONSTRAINT seller_recommendations_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.seller_reputation_ledger ADD CONSTRAINT seller_reputation_ledger_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id);
ALTER TABLE public.seller_settlements ADD CONSTRAINT seller_settlements_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.seller_settlements ADD CONSTRAINT seller_settlements_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id);
ALTER TABLE public.seller_settlements ADD CONSTRAINT seller_settlements_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.service_addons ADD CONSTRAINT service_addons_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.service_availability_schedules ADD CONSTRAINT service_availability_schedules_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.service_availability_schedules ADD CONSTRAINT service_availability_schedules_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.service_booking_addons ADD CONSTRAINT service_booking_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES service_addons(id) ON DELETE CASCADE;
ALTER TABLE public.service_booking_addons ADD CONSTRAINT service_booking_addons_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES service_bookings(id) ON DELETE CASCADE;
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id);
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_rescheduled_from_fkey FOREIGN KEY (rescheduled_from) REFERENCES service_bookings(id);
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id);
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES service_slots(id);
ALTER TABLE public.service_bookings ADD CONSTRAINT service_bookings_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES service_staff(id) ON DELETE SET NULL;
ALTER TABLE public.service_listings ADD CONSTRAINT service_listings_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.service_recurring_configs ADD CONSTRAINT service_recurring_configs_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES service_bookings(id) ON DELETE CASCADE;
ALTER TABLE public.service_recurring_configs ADD CONSTRAINT service_recurring_configs_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.service_slots ADD CONSTRAINT service_slots_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.service_slots ADD CONSTRAINT service_slots_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.service_staff ADD CONSTRAINT service_staff_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.session_feedback ADD CONSTRAINT session_feedback_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES service_bookings(id) ON DELETE CASCADE;
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_endorser_id_fkey FOREIGN KEY (endorser_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.skill_endorsements ADD CONSTRAINT skill_endorsements_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skill_listings(id) ON DELETE CASCADE;
ALTER TABLE public.skill_listings ADD CONSTRAINT skill_listings_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.skill_listings ADD CONSTRAINT skill_listings_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.slot_holds ADD CONSTRAINT slot_holds_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES service_slots(id) ON DELETE CASCADE;
ALTER TABLE public.slot_waitlist ADD CONSTRAINT slot_waitlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.slot_waitlist ADD CONSTRAINT slot_waitlist_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES service_slots(id) ON DELETE CASCADE;
ALTER TABLE public.snag_tickets ADD CONSTRAINT snag_tickets_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES profiles(id);
ALTER TABLE public.snag_tickets ADD CONSTRAINT snag_tickets_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.snag_tickets ADD CONSTRAINT snag_tickets_tower_id_fkey FOREIGN KEY (tower_id) REFERENCES project_towers(id) ON DELETE SET NULL;
ALTER TABLE public.societies ADD CONSTRAINT societies_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.society_activity ADD CONSTRAINT society_activity_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.society_activity ADD CONSTRAINT society_activity_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.society_admins ADD CONSTRAINT society_admins_appointed_by_fkey FOREIGN KEY (appointed_by) REFERENCES profiles(id);
ALTER TABLE public.society_admins ADD CONSTRAINT society_admins_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.society_admins ADD CONSTRAINT society_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.society_budgets ADD CONSTRAINT society_budgets_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_expenses ADD CONSTRAINT society_expenses_added_by_fkey FOREIGN KEY (added_by) REFERENCES profiles(id);
ALTER TABLE public.society_expenses ADD CONSTRAINT society_expenses_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_feature_overrides ADD CONSTRAINT society_feature_overrides_feature_id_fkey FOREIGN KEY (feature_id) REFERENCES platform_features(id) ON DELETE CASCADE;
ALTER TABLE public.society_feature_overrides ADD CONSTRAINT society_feature_overrides_overridden_by_fkey FOREIGN KEY (overridden_by) REFERENCES profiles(id);
ALTER TABLE public.society_feature_overrides ADD CONSTRAINT society_feature_overrides_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.society_features ADD CONSTRAINT society_features_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_income ADD CONSTRAINT society_income_added_by_fkey FOREIGN KEY (added_by) REFERENCES profiles(id);
ALTER TABLE public.society_income ADD CONSTRAINT society_income_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_notices ADD CONSTRAINT society_notices_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES profiles(id);
ALTER TABLE public.society_notices ADD CONSTRAINT society_notices_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_report_cards ADD CONSTRAINT society_report_cards_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_reports ADD CONSTRAINT society_reports_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.society_worker_categories ADD CONSTRAINT society_worker_categories_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.society_workers ADD CONSTRAINT fk_workers_category FOREIGN KEY (category_id) REFERENCES society_worker_categories(id);
ALTER TABLE public.society_workers ADD CONSTRAINT society_workers_registered_by_fkey FOREIGN KEY (registered_by) REFERENCES profiles(id);
ALTER TABLE public.society_workers ADD CONSTRAINT society_workers_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.stock_watchlist ADD CONSTRAINT stock_watchlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.stock_watchlist ADD CONSTRAINT stock_watchlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.subcategories ADD CONSTRAINT subcategories_category_config_id_fkey FOREIGN KEY (category_config_id) REFERENCES category_config(id);
ALTER TABLE public.subscription_deliveries ADD CONSTRAINT subscription_deliveries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.subscription_deliveries ADD CONSTRAINT subscription_deliveries_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES seller_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_feedback ADD CONSTRAINT user_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_notifications ADD CONSTRAINT user_notifications_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.user_notifications ADD CONSTRAINT user_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.visitor_entries ADD CONSTRAINT visitor_entries_parking_slot_id_fkey FOREIGN KEY (parking_slot_id) REFERENCES parking_slots(id);
ALTER TABLE public.visitor_entries ADD CONSTRAINT visitor_entries_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.visitor_entries ADD CONSTRAINT visitor_entries_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.visitor_types ADD CONSTRAINT visitor_types_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.warnings ADD CONSTRAINT warnings_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES profiles(id);
ALTER TABLE public.warnings ADD CONSTRAINT warnings_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);
ALTER TABLE public.worker_attendance ADD CONSTRAINT worker_attendance_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.worker_attendance ADD CONSTRAINT worker_attendance_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES society_workers(id);
ALTER TABLE public.worker_entry_logs ADD CONSTRAINT worker_entry_logs_gate_entry_id_fkey FOREIGN KEY (gate_entry_id) REFERENCES gate_entries(id);
ALTER TABLE public.worker_entry_logs ADD CONSTRAINT worker_entry_logs_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.worker_entry_logs ADD CONSTRAINT worker_entry_logs_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES profiles(id);
ALTER TABLE public.worker_entry_logs ADD CONSTRAINT worker_entry_logs_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES society_workers(id);
ALTER TABLE public.worker_flat_assignments ADD CONSTRAINT worker_flat_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id);
ALTER TABLE public.worker_flat_assignments ADD CONSTRAINT worker_flat_assignments_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.worker_flat_assignments ADD CONSTRAINT worker_flat_assignments_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.worker_flat_assignments ADD CONSTRAINT worker_flat_assignments_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES society_workers(id) ON DELETE CASCADE;
ALTER TABLE public.worker_job_requests ADD CONSTRAINT worker_job_requests_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES profiles(id);
ALTER TABLE public.worker_job_requests ADD CONSTRAINT worker_job_requests_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.worker_job_requests ADD CONSTRAINT worker_job_requests_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE CASCADE;
ALTER TABLE public.worker_leave_records ADD CONSTRAINT worker_leave_records_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.worker_leave_records ADD CONSTRAINT worker_leave_records_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES society_workers(id);
ALTER TABLE public.worker_ratings ADD CONSTRAINT worker_ratings_rated_by_fkey FOREIGN KEY (rated_by) REFERENCES profiles(id);
ALTER TABLE public.worker_ratings ADD CONSTRAINT worker_ratings_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.worker_ratings ADD CONSTRAINT worker_ratings_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES society_workers(id) ON DELETE CASCADE;
ALTER TABLE public.worker_salary_records ADD CONSTRAINT worker_salary_records_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES profiles(id);
ALTER TABLE public.worker_salary_records ADD CONSTRAINT worker_salary_records_society_id_fkey FOREIGN KEY (society_id) REFERENCES societies(id);
ALTER TABLE public.worker_salary_records ADD CONSTRAINT worker_salary_records_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES society_workers(id);]]