[map[index_ddl:CREATE UNIQUE INDEX admin_settings_key_key ON public.admin_settings USING btree (key);
CREATE UNIQUE INDEX admin_settings_pkey ON public.admin_settings USING btree (id);
CREATE UNIQUE INDEX ai_review_log_pkey ON public.ai_review_log USING btree (id);
CREATE INDEX idx_ai_review_log_target ON public.ai_review_log USING btree (target_type, target_id);
CREATE UNIQUE INDEX attribute_block_library_pkey ON public.attribute_block_library USING btree (id);
CREATE UNIQUE INDEX audit_log_pkey ON public.audit_log USING btree (id);
CREATE INDEX idx_audit_log_actor ON public.audit_log USING btree (actor_id, created_at DESC);
CREATE INDEX idx_audit_log_society_created ON public.audit_log USING btree (society_id, created_at DESC);
CREATE UNIQUE INDEX audit_log_archive_pkey ON public.audit_log_archive USING btree (id);
CREATE UNIQUE INDEX authorized_persons_pkey ON public.authorized_persons USING btree (id);
CREATE UNIQUE INDEX badge_config_pkey ON public.badge_config USING btree (id);
CREATE UNIQUE INDEX badge_config_tag_key_key ON public.badge_config USING btree (tag_key);
CREATE UNIQUE INDEX builder_announcements_pkey ON public.builder_announcements USING btree (id);
CREATE UNIQUE INDEX builder_feature_packages_builder_id_package_id_key ON public.builder_feature_packages USING btree (builder_id, package_id);
CREATE UNIQUE INDEX builder_feature_packages_pkey ON public.builder_feature_packages USING btree (id);
CREATE UNIQUE INDEX builder_members_builder_id_user_id_key ON public.builder_members USING btree (builder_id, user_id);
CREATE UNIQUE INDEX builder_members_pkey ON public.builder_members USING btree (id);
CREATE UNIQUE INDEX builder_societies_builder_id_society_id_key ON public.builder_societies USING btree (builder_id, society_id);
CREATE UNIQUE INDEX builder_societies_pkey ON public.builder_societies USING btree (id);
CREATE UNIQUE INDEX builders_pkey ON public.builders USING btree (id);
CREATE UNIQUE INDEX builders_slug_key ON public.builders USING btree (slug);
CREATE UNIQUE INDEX bulletin_comments_pkey ON public.bulletin_comments USING btree (id);
CREATE INDEX idx_bulletin_comments_post ON public.bulletin_comments USING btree (post_id);
CREATE UNIQUE INDEX bulletin_posts_pkey ON public.bulletin_posts USING btree (id);
CREATE INDEX idx_bulletin_posts_created ON public.bulletin_posts USING btree (created_at DESC);
CREATE INDEX idx_bulletin_posts_society ON public.bulletin_posts USING btree (society_id);
CREATE UNIQUE INDEX bulletin_rsvps_pkey ON public.bulletin_rsvps USING btree (id);
CREATE UNIQUE INDEX bulletin_rsvps_post_id_user_id_key ON public.bulletin_rsvps USING btree (post_id, user_id);
CREATE INDEX idx_bulletin_rsvps_post ON public.bulletin_rsvps USING btree (post_id);
CREATE UNIQUE INDEX bulletin_votes_pkey ON public.bulletin_votes USING btree (id);
CREATE UNIQUE INDEX bulletin_votes_post_id_user_id_vote_type_key ON public.bulletin_votes USING btree (post_id, user_id, vote_type);
CREATE INDEX idx_bulletin_votes_post ON public.bulletin_votes USING btree (post_id);
CREATE UNIQUE INDEX call_feedback_pkey ON public.call_feedback USING btree (id);
CREATE INDEX idx_call_feedback_interaction ON public.call_feedback USING btree (interaction_id);
CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree (id);
CREATE UNIQUE INDEX cart_items_pkey ON public.cart_items USING btree (id);
CREATE UNIQUE INDEX cart_items_user_id_product_id_key ON public.cart_items USING btree (user_id, product_id);
CREATE UNIQUE INDEX category_config_category_key ON public.category_config USING btree (category);
CREATE UNIQUE INDEX category_config_pkey ON public.category_config USING btree (id);
CREATE UNIQUE INDEX category_status_flows_pkey ON public.category_status_flows USING btree (id);
CREATE UNIQUE INDEX chat_messages_pkey ON public.chat_messages USING btree (id);
CREATE UNIQUE INDEX collective_buy_participants_pkey ON public.collective_buy_participants USING btree (id);
CREATE UNIQUE INDEX collective_buy_requests_pkey ON public.collective_buy_requests USING btree (id);
CREATE UNIQUE INDEX collective_escalations_pkey ON public.collective_escalations USING btree (id);
CREATE UNIQUE INDEX construction_milestones_pkey ON public.construction_milestones USING btree (id);
CREATE INDEX idx_construction_milestones_society ON public.construction_milestones USING btree (society_id, created_at DESC);
CREATE UNIQUE INDEX coupon_redemptions_pkey ON public.coupon_redemptions USING btree (id);
CREATE UNIQUE INDEX coupons_pkey ON public.coupons USING btree (id);
CREATE UNIQUE INDEX coupons_seller_id_code_key ON public.coupons USING btree (seller_id, code);
CREATE UNIQUE INDEX delivery_addresses_pkey ON public.delivery_addresses USING btree (id);
CREATE INDEX idx_delivery_addresses_user ON public.delivery_addresses USING btree (user_id);
CREATE UNIQUE INDEX delivery_assignments_idempotency_key ON public.delivery_assignments USING btree (idempotency_key);
CREATE UNIQUE INDEX delivery_assignments_order_id_key ON public.delivery_assignments USING btree (order_id);
CREATE UNIQUE INDEX delivery_assignments_pkey ON public.delivery_assignments USING btree (id);
CREATE INDEX idx_delivery_assignments_society ON public.delivery_assignments USING btree (society_id);
CREATE UNIQUE INDEX delivery_locations_pkey ON public.delivery_locations USING btree (id);
CREATE UNIQUE INDEX delivery_partner_pool_pkey ON public.delivery_partner_pool USING btree (id);
CREATE UNIQUE INDEX delivery_partners_pkey ON public.delivery_partners USING btree (id);
CREATE UNIQUE INDEX delivery_tracking_logs_pkey ON public.delivery_tracking_logs USING btree (id);
CREATE UNIQUE INDEX device_tokens_pkey ON public.device_tokens USING btree (id);
CREATE UNIQUE INDEX device_tokens_user_id_token_key ON public.device_tokens USING btree (user_id, token);
CREATE UNIQUE INDEX dispute_comments_pkey ON public.dispute_comments USING btree (id);
CREATE UNIQUE INDEX dispute_tickets_pkey ON public.dispute_tickets USING btree (id);
CREATE INDEX idx_dispute_tickets_society_created ON public.dispute_tickets USING btree (society_id, created_at DESC);
CREATE INDEX idx_dispute_tickets_society_status ON public.dispute_tickets USING btree (society_id, status);
CREATE UNIQUE INDEX domestic_help_attendance_pkey ON public.domestic_help_attendance USING btree (id);
CREATE UNIQUE INDEX domestic_help_entries_pkey ON public.domestic_help_entries USING btree (id);
CREATE UNIQUE INDEX emergency_broadcasts_pkey ON public.emergency_broadcasts USING btree (id);
CREATE UNIQUE INDEX expense_flags_pkey ON public.expense_flags USING btree (id);
CREATE UNIQUE INDEX expense_views_expense_id_user_id_key ON public.expense_views USING btree (expense_id, user_id);
CREATE UNIQUE INDEX expense_views_pkey ON public.expense_views USING btree (id);
CREATE UNIQUE INDEX favorites_pkey ON public.favorites USING btree (id);
CREATE UNIQUE INDEX favorites_user_id_seller_id_key ON public.favorites USING btree (user_id, seller_id);
CREATE UNIQUE INDEX feature_package_items_package_id_feature_id_key ON public.feature_package_items USING btree (package_id, feature_id);
CREATE UNIQUE INDEX feature_package_items_pkey ON public.feature_package_items USING btree (id);
CREATE UNIQUE INDEX feature_packages_pkey ON public.feature_packages USING btree (id);
CREATE UNIQUE INDEX featured_items_pkey ON public.featured_items USING btree (id);
CREATE UNIQUE INDEX gate_entries_pkey ON public.gate_entries USING btree (id);
CREATE INDEX idx_gate_entries_society_time ON public.gate_entries USING btree (society_id, entry_time DESC);
CREATE UNIQUE INDEX help_requests_pkey ON public.help_requests USING btree (id);
CREATE INDEX idx_help_requests_society ON public.help_requests USING btree (society_id);
CREATE UNIQUE INDEX help_responses_pkey ON public.help_responses USING btree (id);
CREATE INDEX idx_help_responses_request ON public.help_responses USING btree (request_id);
CREATE UNIQUE INDEX inspection_checklists_pkey ON public.inspection_checklists USING btree (id);
CREATE UNIQUE INDEX inspection_items_pkey ON public.inspection_items USING btree (id);
CREATE UNIQUE INDEX job_tts_cache_pkey ON public.job_tts_cache USING btree (id);
CREATE INDEX idx_maintenance_dues_society_month ON public.maintenance_dues USING btree (society_id, month DESC);
CREATE UNIQUE INDEX maintenance_dues_pkey ON public.maintenance_dues USING btree (id);
CREATE UNIQUE INDEX manual_entry_requests_pkey ON public.manual_entry_requests USING btree (id);
CREATE INDEX idx_marketplace_events_type ON public.marketplace_events USING btree (event_type, created_at DESC);
CREATE UNIQUE INDEX marketplace_events_pkey ON public.marketplace_events USING btree (id);
CREATE UNIQUE INDEX milestone_reactions_milestone_id_user_id_key ON public.milestone_reactions USING btree (milestone_id, user_id);
CREATE UNIQUE INDEX milestone_reactions_pkey ON public.milestone_reactions USING btree (id);
CREATE UNIQUE INDEX notification_preferences_pkey ON public.notification_preferences USING btree (id);
CREATE INDEX idx_notification_queue_retry ON public.notification_queue USING btree (status, next_retry_at);
CREATE INDEX idx_notification_queue_status ON public.notification_queue USING btree (status, created_at) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX notification_queue_pkey ON public.notification_queue USING btree (id);
CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);
CREATE UNIQUE INDEX order_status_config_pkey ON public.order_status_config USING btree (id);
CREATE INDEX idx_orders_buyer_id ON public.orders USING btree (buyer_id);
CREATE INDEX idx_orders_buyer_status ON public.orders USING btree (buyer_id, status);
CREATE UNIQUE INDEX idx_orders_idempotency_key ON public.orders USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_orders_seller_id ON public.orders USING btree (seller_id);
CREATE INDEX idx_orders_seller_status ON public.orders USING btree (seller_id, status);
CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);
CREATE UNIQUE INDEX orders_archive_pkey ON public.orders_archive USING btree (id);
CREATE UNIQUE INDEX parcel_entries_pkey ON public.parcel_entries USING btree (id);
CREATE INDEX idx_parent_groups_slug ON public.parent_groups USING btree (slug);
CREATE UNIQUE INDEX parent_groups_pkey ON public.parent_groups USING btree (id);
CREATE UNIQUE INDEX parent_groups_slug_key ON public.parent_groups USING btree (slug);
CREATE UNIQUE INDEX parking_slots_pkey ON public.parking_slots USING btree (id);
CREATE UNIQUE INDEX parking_slots_society_id_slot_number_key ON public.parking_slots USING btree (society_id, slot_number);
CREATE UNIQUE INDEX parking_violations_pkey ON public.parking_violations USING btree (id);
CREATE UNIQUE INDEX payment_milestones_pkey ON public.payment_milestones USING btree (id);
CREATE UNIQUE INDEX payment_records_pkey ON public.payment_records USING btree (id);
CREATE UNIQUE INDEX payment_settlements_pkey ON public.payment_settlements USING btree (id);
CREATE INDEX idx_phone_otp_phone_status ON public.phone_otp_verifications USING btree (phone_number, status, created_at DESC);
CREATE UNIQUE INDEX phone_otp_verifications_pkey ON public.phone_otp_verifications USING btree (id);
CREATE UNIQUE INDEX platform_features_feature_key_key ON public.platform_features USING btree (feature_key);
CREATE UNIQUE INDEX platform_features_pkey ON public.platform_features USING btree (id);
CREATE UNIQUE INDEX price_history_pkey ON public.price_history USING btree (id);
CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);
CREATE UNIQUE INDEX idx_profiles_email_unique ON public.profiles USING btree (email) WHERE ((email IS NOT NULL) AND (email <> ''::text));
CREATE UNIQUE INDEX idx_profiles_phone_unique ON public.profiles USING btree (phone) WHERE ((phone IS NOT NULL) AND (phone <> ''::text));
CREATE INDEX idx_profiles_society_id ON public.profiles USING btree (society_id);
CREATE INDEX idx_profiles_society_verification ON public.profiles USING btree (society_id, verification_status);
CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE UNIQUE INDEX project_answers_pkey ON public.project_answers USING btree (id);
CREATE UNIQUE INDEX project_documents_pkey ON public.project_documents USING btree (id);
CREATE UNIQUE INDEX project_questions_pkey ON public.project_questions USING btree (id);
CREATE UNIQUE INDEX project_towers_pkey ON public.project_towers USING btree (id);
CREATE UNIQUE INDEX push_logs_pkey ON public.push_logs USING btree (id);
CREATE UNIQUE INDEX rate_limits_key_key ON public.rate_limits USING btree (key);
CREATE UNIQUE INDEX rate_limits_pkey ON public.rate_limits USING btree (id);
CREATE UNIQUE INDEX reports_pkey ON public.reports USING btree (id);
CREATE UNIQUE INDEX resident_payments_milestone_id_resident_id_key ON public.resident_payments USING btree (milestone_id, resident_id);
CREATE UNIQUE INDEX resident_payments_pkey ON public.resident_payments USING btree (id);
CREATE UNIQUE INDEX reviews_order_id_key ON public.reviews USING btree (order_id);
CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);
CREATE UNIQUE INDEX search_demand_log_pkey ON public.search_demand_log USING btree (id);
CREATE UNIQUE INDEX security_staff_pkey ON public.security_staff USING btree (id);
CREATE UNIQUE INDEX security_staff_user_id_role_key ON public.security_staff USING btree (user_id, role);
CREATE INDEX idx_sci_buyer_id ON public.seller_contact_interactions USING btree (buyer_id);
CREATE INDEX idx_sci_seller_id ON public.seller_contact_interactions USING btree (seller_id);
CREATE UNIQUE INDEX seller_contact_interactions_pkey ON public.seller_contact_interactions USING btree (id);
CREATE INDEX idx_scm_conversation ON public.seller_conversation_messages USING btree (conversation_id, created_at);
CREATE UNIQUE INDEX seller_conversation_messages_pkey ON public.seller_conversation_messages USING btree (id);
CREATE INDEX idx_sc_buyer_seller ON public.seller_conversations USING btree (buyer_id, seller_id);
CREATE UNIQUE INDEX seller_conversations_buyer_id_seller_id_product_id_key ON public.seller_conversations USING btree (buyer_id, seller_id, product_id);
CREATE UNIQUE INDEX seller_conversations_pkey ON public.seller_conversations USING btree (id);
CREATE UNIQUE INDEX seller_form_configs_pkey ON public.seller_form_configs USING btree (id);
CREATE UNIQUE INDEX seller_licenses_pkey ON public.seller_licenses USING btree (id);
CREATE UNIQUE INDEX seller_licenses_seller_id_group_id_key ON public.seller_licenses USING btree (seller_id, group_id);
CREATE INDEX idx_seller_coords ON public.seller_profiles USING btree (latitude, longitude);
CREATE INDEX idx_seller_profiles_society_id ON public.seller_profiles USING btree (society_id);
CREATE INDEX idx_seller_profiles_society_verification ON public.seller_profiles USING btree (society_id, verification_status);
CREATE UNIQUE INDEX seller_profiles_pkey ON public.seller_profiles USING btree (id);
CREATE UNIQUE INDEX seller_profiles_user_group_key ON public.seller_profiles USING btree (user_id, primary_group);
CREATE UNIQUE INDEX seller_recommendations_pkey ON public.seller_recommendations USING btree (id);
CREATE UNIQUE INDEX seller_recommendations_seller_id_recommender_id_key ON public.seller_recommendations USING btree (seller_id, recommender_id);
CREATE UNIQUE INDEX seller_reputation_ledger_pkey ON public.seller_reputation_ledger USING btree (id);
CREATE UNIQUE INDEX seller_settlements_order_id_key ON public.seller_settlements USING btree (order_id);
CREATE UNIQUE INDEX seller_settlements_pkey ON public.seller_settlements USING btree (id);
CREATE UNIQUE INDEX service_addons_pkey ON public.service_addons USING btree (id);
CREATE INDEX idx_service_availability_seller ON public.service_availability_schedules USING btree (seller_id);
CREATE UNIQUE INDEX service_availability_schedule_seller_id_product_id_day_of_w_key ON public.service_availability_schedules USING btree (seller_id, product_id, day_of_week);
CREATE UNIQUE INDEX service_availability_schedules_pkey ON public.service_availability_schedules USING btree (id);
CREATE UNIQUE INDEX uq_service_availability_seller_day_null_product ON public.service_availability_schedules USING btree (seller_id, day_of_week) WHERE (product_id IS NULL);
CREATE UNIQUE INDEX uq_service_availability_seller_product_day ON public.service_availability_schedules USING btree (seller_id, product_id, day_of_week);
CREATE UNIQUE INDEX uq_service_availability_seller_product_day_notnull ON public.service_availability_schedules USING btree (seller_id, product_id, day_of_week) WHERE (product_id IS NOT NULL);
CREATE UNIQUE INDEX service_booking_addons_pkey ON public.service_booking_addons USING btree (id);
CREATE INDEX idx_service_bookings_buyer ON public.service_bookings USING btree (buyer_id);
CREATE INDEX idx_service_bookings_buyer_slot ON public.service_bookings USING btree (buyer_id, slot_id) WHERE (status <> ALL (ARRAY['cancelled'::text, 'no_show'::text]));
CREATE INDEX idx_service_bookings_date_status ON public.service_bookings USING btree (booking_date, status);
CREATE INDEX idx_service_bookings_seller ON public.service_bookings USING btree (seller_id);
CREATE INDEX idx_service_bookings_slot ON public.service_bookings USING btree (slot_id);
CREATE UNIQUE INDEX idx_unique_buyer_slot_active ON public.service_bookings USING btree (buyer_id, slot_id) WHERE (status <> ALL (ARRAY['cancelled'::text, 'no_show'::text]));
CREATE UNIQUE INDEX service_bookings_pkey ON public.service_bookings USING btree (id);
CREATE UNIQUE INDEX service_listings_pkey ON public.service_listings USING btree (id);
CREATE UNIQUE INDEX service_listings_product_id_key ON public.service_listings USING btree (product_id);
CREATE UNIQUE INDEX service_recurring_configs_pkey ON public.service_recurring_configs USING btree (id);
CREATE INDEX idx_service_slots_product_date ON public.service_slots USING btree (product_id, slot_date);
CREATE INDEX idx_service_slots_seller_date ON public.service_slots USING btree (seller_id, slot_date);
CREATE UNIQUE INDEX service_slots_pkey ON public.service_slots USING btree (id);
CREATE UNIQUE INDEX service_slots_product_id_slot_date_start_time_key ON public.service_slots USING btree (product_id, slot_date, start_time);
CREATE UNIQUE INDEX uq_service_slots_seller_product_date_time ON public.service_slots USING btree (seller_id, product_id, slot_date, start_time);
CREATE UNIQUE INDEX service_staff_pkey ON public.service_staff USING btree (id);
CREATE UNIQUE INDEX session_feedback_booking_id_buyer_id_key ON public.session_feedback USING btree (booking_id, buyer_id);
CREATE UNIQUE INDEX session_feedback_pkey ON public.session_feedback USING btree (id);
CREATE INDEX idx_skill_endorsements_skill ON public.skill_endorsements USING btree (skill_id);
CREATE UNIQUE INDEX skill_endorsements_pkey ON public.skill_endorsements USING btree (id);
CREATE UNIQUE INDEX skill_endorsements_skill_id_endorser_id_key ON public.skill_endorsements USING btree (skill_id, endorser_id);
CREATE INDEX idx_skill_listings_society ON public.skill_listings USING btree (society_id);
CREATE UNIQUE INDEX skill_listings_pkey ON public.skill_listings USING btree (id);
CREATE INDEX idx_slot_holds_expires ON public.slot_holds USING btree (expires_at);
CREATE INDEX idx_slot_holds_slot_id ON public.slot_holds USING btree (slot_id);
CREATE UNIQUE INDEX slot_holds_pkey ON public.slot_holds USING btree (id);
CREATE INDEX idx_slot_waitlist_slot ON public.slot_waitlist USING btree (slot_id);
CREATE UNIQUE INDEX slot_waitlist_pkey ON public.slot_waitlist USING btree (id);
CREATE UNIQUE INDEX slot_waitlist_slot_id_buyer_id_key ON public.slot_waitlist USING btree (slot_id, buyer_id);
CREATE INDEX idx_snag_tickets_society_status ON public.snag_tickets USING btree (society_id, status);
CREATE UNIQUE INDEX snag_tickets_pkey ON public.snag_tickets USING btree (id);
CREATE UNIQUE INDEX societies_invite_code_key ON public.societies USING btree (invite_code);
CREATE UNIQUE INDEX societies_pkey ON public.societies USING btree (id);
CREATE UNIQUE INDEX societies_slug_key ON public.societies USING btree (slug);
CREATE INDEX idx_society_activity_society_created ON public.society_activity USING btree (society_id, created_at DESC);
CREATE UNIQUE INDEX society_activity_pkey ON public.society_activity USING btree (id);
CREATE UNIQUE INDEX society_admins_pkey ON public.society_admins USING btree (id);
CREATE UNIQUE INDEX society_admins_society_id_user_id_key ON public.society_admins USING btree (society_id, user_id);
CREATE UNIQUE INDEX society_budgets_pkey ON public.society_budgets USING btree (id);
CREATE INDEX idx_society_expenses_society_created ON public.society_expenses USING btree (society_id, created_at DESC);
CREATE UNIQUE INDEX society_expenses_pkey ON public.society_expenses USING btree (id);
CREATE UNIQUE INDEX society_feature_overrides_pkey ON public.society_feature_overrides USING btree (id);
CREATE UNIQUE INDEX society_feature_overrides_society_id_feature_id_key ON public.society_feature_overrides USING btree (society_id, feature_id);
CREATE UNIQUE INDEX society_features_pkey ON public.society_features USING btree (id);
CREATE UNIQUE INDEX society_income_pkey ON public.society_income USING btree (id);
CREATE UNIQUE INDEX society_notices_pkey ON public.society_notices USING btree (id);
CREATE UNIQUE INDEX society_report_cards_pkey ON public.society_report_cards USING btree (id);
CREATE UNIQUE INDEX society_reports_pkey ON public.society_reports USING btree (id);
CREATE UNIQUE INDEX society_reports_society_id_report_month_key ON public.society_reports USING btree (society_id, report_month);
CREATE UNIQUE INDEX society_worker_categories_pkey ON public.society_worker_categories USING btree (id);
CREATE UNIQUE INDEX society_worker_categories_society_id_name_key ON public.society_worker_categories USING btree (society_id, name);
CREATE UNIQUE INDEX society_workers_pkey ON public.society_workers USING btree (id);
CREATE UNIQUE INDEX society_workers_user_id_society_id_key ON public.society_workers USING btree (user_id, society_id);
CREATE UNIQUE INDEX stock_watchlist_pkey ON public.stock_watchlist USING btree (id);
CREATE UNIQUE INDEX subcategories_pkey ON public.subcategories USING btree (id);
CREATE UNIQUE INDEX subscription_deliveries_pkey ON public.subscription_deliveries USING btree (id);
CREATE INDEX idx_subscriptions_buyer ON public.subscriptions USING btree (buyer_id);
CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);
CREATE UNIQUE INDEX supported_languages_pkey ON public.supported_languages USING btree (id);
CREATE UNIQUE INDEX system_settings_pkey ON public.system_settings USING btree (key);
CREATE UNIQUE INDEX test_results_pkey ON public.test_results USING btree (id);
CREATE INDEX idx_trigger_errors_created_at ON public.trigger_errors USING btree (created_at DESC);
CREATE UNIQUE INDEX trigger_errors_pkey ON public.trigger_errors USING btree (id);
CREATE UNIQUE INDEX trust_tier_config_pkey ON public.trust_tier_config USING btree (id);
CREATE UNIQUE INDEX trust_tier_config_tier_key_key ON public.trust_tier_config USING btree (tier_key);
CREATE UNIQUE INDEX user_feedback_pkey ON public.user_feedback USING btree (id);
CREATE UNIQUE INDEX idx_user_notifications_queue_item ON public.user_notifications USING btree (queue_item_id) WHERE (queue_item_id IS NOT NULL);
CREATE INDEX idx_user_notifications_user_read ON public.user_notifications USING btree (user_id, is_read, created_at DESC);
CREATE UNIQUE INDEX user_notifications_pkey ON public.user_notifications USING btree (id);
CREATE INDEX idx_user_roles_user_role ON public.user_roles USING btree (user_id, role);
CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);
CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);
CREATE INDEX idx_visitor_entries_society_status ON public.visitor_entries USING btree (society_id, status);
CREATE UNIQUE INDEX visitor_entries_pkey ON public.visitor_entries USING btree (id);
CREATE UNIQUE INDEX visitor_types_pkey ON public.visitor_types USING btree (id);
CREATE UNIQUE INDEX warnings_pkey ON public.warnings USING btree (id);
CREATE UNIQUE INDEX worker_attendance_pkey ON public.worker_attendance USING btree (id);
CREATE UNIQUE INDEX worker_entry_logs_pkey ON public.worker_entry_logs USING btree (id);
CREATE UNIQUE INDEX worker_flat_assignments_pkey ON public.worker_flat_assignments USING btree (id);
CREATE UNIQUE INDEX worker_flat_assignments_worker_id_flat_number_society_id_key ON public.worker_flat_assignments USING btree (worker_id, flat_number, society_id);
CREATE UNIQUE INDEX worker_job_requests_pkey ON public.worker_job_requests USING btree (id);
CREATE UNIQUE INDEX worker_leave_records_pkey ON public.worker_leave_records USING btree (id);
CREATE UNIQUE INDEX worker_ratings_pkey ON public.worker_ratings USING btree (id);
CREATE UNIQUE INDEX worker_ratings_worker_id_rated_by_month_key ON public.worker_ratings USING btree (worker_id, rated_by, month);
CREATE UNIQUE INDEX worker_salary_records_pkey ON public.worker_salary_records USING btree (id);]]