[map[trigger_ddl:CREATE TRIGGER trg_update_updated_at_admin_settings BEFORE UPDATE ON admin_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_admin_settings_updated_at BEFORE UPDATE ON admin_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_builders BEFORE UPDATE ON builders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_bulletin_comment_count AFTER INSERT OR DELETE ON bulletin_comments FOR EACH ROW EXECUTE FUNCTION update_bulletin_comment_count();
CREATE TRIGGER trg_log_bulletin_activity AFTER INSERT ON bulletin_posts FOR EACH ROW EXECUTE FUNCTION log_bulletin_activity();
CREATE TRIGGER trg_update_updated_at_bulletin_posts BEFORE UPDATE ON bulletin_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_bulletin_posts_updated_at BEFORE UPDATE ON bulletin_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_bulletin_vote_count AFTER INSERT OR DELETE ON bulletin_votes FOR EACH ROW EXECUTE FUNCTION update_bulletin_vote_count();
CREATE TRIGGER validate_cart_item_store_availability_trigger BEFORE INSERT OR UPDATE OF product_id, quantity ON cart_items FOR EACH ROW EXECUTE FUNCTION validate_cart_item_store_availability();
CREATE TRIGGER trg_sync_products_action_type_on_category_tx_change AFTER UPDATE OF transaction_type ON category_config FOR EACH ROW EXECUTE FUNCTION sync_products_action_type_on_category_tx_change();
CREATE TRIGGER trg_update_updated_at_category_config BEFORE UPDATE ON category_config FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_validate_category_layout_type BEFORE INSERT OR UPDATE ON category_config FOR EACH ROW EXECUTE FUNCTION validate_category_layout_type();
CREATE TRIGGER update_category_config_updated_at BEFORE UPDATE ON category_config FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_coupons BEFORE UPDATE ON coupons FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_coupons_updated_at BEFORE UPDATE ON coupons FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_delivery_addresses_updated_at BEFORE UPDATE ON delivery_addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_delivery_assignments BEFORE UPDATE ON delivery_assignments FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_delivery_assignments_updated_at BEFORE UPDATE ON delivery_assignments FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_delivery_partners BEFORE UPDATE ON delivery_partners FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_delivery_partners_updated_at BEFORE UPDATE ON delivery_partners FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_device_tokens_updated_at BEFORE UPDATE ON device_tokens FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_dispute_status_notification AFTER UPDATE ON dispute_tickets FOR EACH ROW EXECUTE FUNCTION enqueue_dispute_status_notification();
CREATE TRIGGER trg_log_dispute_activity AFTER INSERT ON dispute_tickets FOR EACH ROW EXECUTE FUNCTION log_dispute_activity();
CREATE TRIGGER trg_update_updated_at_domestic_help_entries BEFORE UPDATE ON domestic_help_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_feature_packages BEFORE UPDATE ON feature_packages FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_feature_packages_updated_at BEFORE UPDATE ON feature_packages FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_featured_items BEFORE UPDATE ON featured_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_featured_items_updated_at BEFORE UPDATE ON featured_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_log_help_request_activity AFTER INSERT ON help_requests FOR EACH ROW EXECUTE FUNCTION log_help_request_activity();
CREATE TRIGGER trg_update_help_response_count AFTER INSERT OR DELETE ON help_responses FOR EACH ROW EXECUTE FUNCTION update_help_response_count();
CREATE TRIGGER trg_update_updated_at_inspection_checklists BEFORE UPDATE ON inspection_checklists FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_inspection_items BEFORE UPDATE ON inspection_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_process_notification_queue_realtime AFTER INSERT ON notification_queue FOR EACH ROW EXECUTE FUNCTION trigger_process_notification_queue();
CREATE TRIGGER update_order_items_updated_at BEFORE UPDATE ON order_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_create_settlement_on_delivery AFTER UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION create_settlement_on_delivery();
CREATE TRIGGER trg_enqueue_new_order_notification AFTER INSERT ON orders FOR EACH ROW EXECUTE FUNCTION fn_enqueue_new_order_notification();
CREATE TRIGGER trg_enqueue_order_status_notification AFTER UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION fn_enqueue_order_status_notification();
CREATE TRIGGER trg_log_order_activity AFTER INSERT OR UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION log_order_activity();
CREATE TRIGGER trg_recompute_seller_stats AFTER UPDATE OF status ON orders FOR EACH ROW EXECUTE FUNCTION trigger_recompute_seller_stats();
CREATE TRIGGER trg_set_order_society_id BEFORE INSERT ON orders FOR EACH ROW EXECUTE FUNCTION set_order_society_id();
CREATE TRIGGER trg_update_updated_at_orders BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_parent_groups_updated_at BEFORE UPDATE ON parent_groups FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_payment_records_updated_at BEFORE UPDATE ON payment_records FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_settlement_notification AFTER INSERT ON payment_settlements FOR EACH ROW EXECUTE FUNCTION enqueue_settlement_notification();
CREATE TRIGGER update_platform_features_updated_at BEFORE UPDATE ON platform_features FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER check_seller_license_trigger BEFORE INSERT ON products FOR EACH ROW EXECUTE FUNCTION check_seller_license();
CREATE TRIGGER trg_enqueue_product_review_notification AFTER INSERT OR UPDATE OF approval_status ON products FOR EACH ROW EXECUTE FUNCTION enqueue_product_review_notification();
CREATE TRIGGER trg_log_price_change AFTER UPDATE ON products FOR EACH ROW EXECUTE FUNCTION log_price_change();
CREATE TRIGGER trg_set_product_action_type_from_category BEFORE INSERT OR UPDATE OF category, action_type ON products FOR EACH ROW EXECUTE FUNCTION set_product_action_type_from_category();
CREATE TRIGGER trg_update_updated_at_products BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_auto_approve_resident BEFORE INSERT ON profiles FOR EACH ROW EXECUTE FUNCTION auto_approve_resident();
CREATE TRIGGER trg_update_updated_at_profiles BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_reports_updated_at BEFORE UPDATE ON reports FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_review_notification AFTER INSERT ON reviews FOR EACH ROW EXECUTE FUNCTION enqueue_review_notification();
CREATE TRIGGER trg_update_seller_rating AFTER INSERT OR UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION update_seller_rating();
CREATE TRIGGER update_rating_on_review AFTER INSERT OR UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION update_seller_rating();
CREATE TRIGGER trg_update_conversation_last_message AFTER INSERT ON seller_conversation_messages FOR EACH ROW EXECUTE FUNCTION update_conversation_last_message();
CREATE TRIGGER trg_update_updated_at_seller_profiles BEFORE UPDATE ON seller_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_validate_seller_location_on_approval BEFORE UPDATE ON seller_profiles FOR EACH ROW EXECUTE FUNCTION validate_seller_location_on_approval();
CREATE TRIGGER update_seller_profiles_updated_at BEFORE UPDATE ON seller_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_service_bookings_updated_at BEFORE UPDATE ON service_bookings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER set_service_listings_updated_at BEFORE UPDATE ON service_listings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_recurring_config_updated_at BEFORE UPDATE ON service_recurring_configs FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_notify_waitlist_on_slot_release AFTER UPDATE OF booked_count ON service_slots FOR EACH ROW EXECUTE FUNCTION notify_waitlist_on_slot_release();
CREATE TRIGGER update_service_staff_updated_at BEFORE UPDATE ON service_staff FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_validate_session_feedback_rating BEFORE INSERT OR UPDATE ON session_feedback FOR EACH ROW EXECUTE FUNCTION validate_session_feedback_rating();
CREATE TRIGGER trg_update_updated_at_skill_listings BEFORE UPDATE ON skill_listings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_update_updated_at_societies BEFORE UPDATE ON societies FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_societies_updated_at BEFORE UPDATE ON societies FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_validate_society_admin_limit BEFORE INSERT ON society_admins FOR EACH ROW EXECUTE FUNCTION validate_society_admin_limit();
CREATE TRIGGER trg_update_worker_categories_updated_at BEFORE UPDATE ON society_worker_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_society_workers_updated_at BEFORE UPDATE ON society_workers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_worker_jobs_updated_at BEFORE UPDATE ON worker_job_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at();]]