INSERT INTO attribute_block_library (block_type, display_name, description, icon, category_hints, schema, renderer_type, display_order, is_active) VALUES
('nutrition_info', 'Nutrition Info', 'Calories, protein, carbs and other nutritional data', '🥗', ARRAY['home_food','bakery','snacks'], '{"fields":[{"key":"calories","label":"Calories","type":"text"},{"key":"protein","label":"Protein","type":"text"},{"key":"carbs","label":"Carbs","type":"text"},{"key":"fat","label":"Fat","type":"text"},{"key":"fiber","label":"Fiber","type":"text"}]}'::jsonb, 'key_value', 10, true),
('allergen_info', 'Allergen Info', 'Allergen and dietary warnings', '⚠️', ARRAY['home_food','bakery','snacks'], '{"fields":[{"key":"contains","label":"Contains","type":"text"},{"key":"may_contain","label":"May Contain","type":"text"},{"key":"free_from","label":"Free From","type":"tag_input"}]}'::jsonb, 'badge_list', 11, true),
('course_details', 'Course Details', 'Batch size, schedule, level and inclusions', '📚', ARRAY['coaching','tuition'], '{"fields":[{"key":"level","label":"Level","type":"select","options":["Beginner","Intermediate","Advanced","All levels"]},{"key":"batch_size","label":"Batch Size","type":"text"},{"key":"schedule","label":"Schedule","type":"text"},{"key":"includes","label":"Includes","type":"text"},{"key":"duration","label":"Duration","type":"text"}]}'::jsonb, 'key_value', 12, true),
('session_details', 'Session Details', 'Yoga/fitness session information', '🧘', ARRAY['yoga','fitness'], '{"fields":[{"key":"level","label":"Level","type":"select","options":["Beginner","Intermediate","Advanced","All levels","Intermediate-Advanced"]},{"key":"batch_size","label":"Batch Size","type":"text"},{"key":"equipment","label":"Equipment","type":"text"},{"key":"location","label":"Location","type":"text"},{"key":"intensity","label":"Intensity","type":"select","options":["Low","Medium","High"]},{"key":"calories_burn","label":"Calories Burn","type":"text"},{"key":"special","label":"Special Notes","type":"text"}]}'::jsonb, 'key_value', 13, true),
('product_specs', 'Product Specifications', 'Technical specs for physical products', '📋', ARRAY['electronics','furniture','kitchen','clothing'], '{"fields":[{"key":"material","label":"Material","type":"text"},{"key":"compatibility","label":"Compatibility","type":"text"},{"key":"color_options","label":"Color Options","type":"text"},{"key":"warranty","label":"Warranty","type":"text"},{"key":"wattage","label":"Wattage","type":"text"},{"key":"ports","label":"Ports","type":"text"},{"key":"protocol","label":"Protocol","type":"text"},{"key":"weight","label":"Weight","type":"text"},{"key":"dimensions","label":"Dimensions","type":"text"}]}'::jsonb, 'key_value', 14, true)
ON CONFLICT (block_type) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  category_hints = EXCLUDED.category_hints,
  schema = EXCLUDED.schema,
  renderer_type = EXCLUDED.renderer_type,
  is_active = true;