ALTER TABLE public.notification_preferences ADD COLUMN IF NOT EXISTS chat boolean DEFAULT true NOT NULL;
ALTER TABLE public.notification_preferences ADD COLUMN IF NOT EXISTS orders boolean DEFAULT true NOT NULL;
ALTER TABLE public.notification_preferences ADD COLUMN IF NOT EXISTS promotions boolean DEFAULT true NOT NULL;
ALTER TABLE public.notification_preferences ADD COLUMN IF NOT EXISTS sounds boolean DEFAULT true NOT NULL;
ALTER TABLE public.parcel_entries ADD COLUMN IF NOT EXISTS logged_by uuid;
ALTER TABLE public.parcel_entries ADD COLUMN IF NOT EXISTS notified_at timestamp with time zone;
ALTER TABLE public.parent_groups ADD COLUMN IF NOT EXISTS layout_type text DEFAULT 'ecommerce'::text;
ALTER TABLE public.parent_groups ADD COLUMN IF NOT EXISTS placeholder_hint text;
ALTER TABLE public.parking_slots ADD COLUMN IF NOT EXISTS assigned_to uuid;
ALTER TABLE public.parking_slots ADD COLUMN IF NOT EXISTS is_occupied boolean DEFAULT false NOT NULL;
ALTER TABLE public.parking_slots ADD COLUMN IF NOT EXISTS tower_id uuid;
ALTER TABLE public.parking_slots ADD COLUMN IF NOT EXISTS vehicle_number text;
ALTER TABLE public.parking_slots ADD COLUMN IF NOT EXISTS vehicle_type text;
ALTER TABLE public.payment_records ADD COLUMN IF NOT EXISTS payment_collection text DEFAULT 'direct'::text NOT NULL;
ALTER TABLE public.payment_records ADD COLUMN IF NOT EXISTS payment_mode text DEFAULT 'offline'::text NOT NULL;
ALTER TABLE public.payment_records ADD COLUMN IF NOT EXISTS razorpay_payment_id text;
ALTER TABLE public.payment_records ADD COLUMN IF NOT EXISTS society_id uuid;
ALTER TABLE public.platform_features ADD COLUMN IF NOT EXISTS audience text[];
ALTER TABLE public.platform_features ADD COLUMN IF NOT EXISTS capabilities text[];
ALTER TABLE public.platform_features ADD COLUMN IF NOT EXISTS icon_name text;
ALTER TABLE public.platform_features ADD COLUMN IF NOT EXISTS is_experimental boolean DEFAULT false NOT NULL;
ALTER TABLE public.platform_features ADD COLUMN IF NOT EXISTS route text;
ALTER TABLE public.platform_features ADD COLUMN IF NOT EXISTS tagline text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS cuisine_type text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS delivery_time_text text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS minimum_charge numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS service_scope text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS society_id uuid;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tags text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_while_pending boolean DEFAULT false NOT NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS visit_charge numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS warranty_period text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS has_seen_onboarding boolean DEFAULT false NOT NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone_verified boolean DEFAULT false NOT NULL;
ALTER TABLE public.project_questions ADD COLUMN IF NOT EXISTS is_answered boolean DEFAULT false NOT NULL;
ALTER TABLE public.project_questions ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false NOT NULL;
ALTER TABLE public.project_towers ADD COLUMN IF NOT EXISTS current_percentage integer DEFAULT 0 NOT NULL;
ALTER TABLE public.project_towers ADD COLUMN IF NOT EXISTS current_stage text DEFAULT 'foundation'::text NOT NULL;
ALTER TABLE public.project_towers ADD COLUMN IF NOT EXISTS delay_category text;
ALTER TABLE public.project_towers ADD COLUMN IF NOT EXISTS delay_reason text;
ALTER TABLE public.project_towers ADD COLUMN IF NOT EXISTS revised_completion date;
ALTER TABLE public.push_logs ADD COLUMN IF NOT EXISTS level text DEFAULT 'info'::text NOT NULL;
ALTER TABLE public.push_logs ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE public.push_logs ADD COLUMN IF NOT EXISTS metadata jsonb;
ALTER TABLE public.societies ADD COLUMN IF NOT EXISTS normalized_name text;
ALTER TABLE public.society_expenses ADD COLUMN IF NOT EXISTS invoice_url text;
ALTER TABLE public.society_expenses ADD COLUMN IF NOT EXISTS vendor_name text;
ALTER TABLE public.society_notices ADD COLUMN IF NOT EXISTS attachment_urls text[];
ALTER TABLE public.society_notices ADD COLUMN IF NOT EXISTS category text DEFAULT 'general'::text NOT NULL;
ALTER TABLE public.society_notices ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false NOT NULL;
ALTER TABLE public.society_worker_categories ADD COLUMN IF NOT EXISTS display_order integer DEFAULT 0;
ALTER TABLE public.society_worker_categories ADD COLUMN IF NOT EXISTS requires_background_check boolean DEFAULT false;
ALTER TABLE public.society_worker_categories ADD COLUMN IF NOT EXISTS requires_security_training boolean DEFAULT false;
ALTER TABLE public.society_worker_categories ADD COLUMN IF NOT EXISTS society_id uuid;
ALTER TABLE public.society_worker_categories ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE public.society_workers ADD COLUMN IF NOT EXISTS deactivated_at timestamp with time zone;
ALTER TABLE public.society_workers ADD COLUMN IF NOT EXISTS is_available boolean DEFAULT true;
ALTER TABLE public.society_workers ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE public.society_workers ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{}'::text[];
ALTER TABLE public.society_workers ADD COLUMN IF NOT EXISTS skills jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.society_workers ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS description_placeholder text;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS duration_label text;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS name_placeholder text;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS price_label text;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS show_duration_field boolean DEFAULT false;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS show_veg_toggle boolean DEFAULT false;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS supports_addons boolean;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS supports_recurring boolean;
ALTER TABLE public.subcategories ADD COLUMN IF NOT EXISTS supports_staff_assignment boolean;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS badge_color text DEFAULT 'muted'::text NOT NULL;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS display_order integer DEFAULT 0 NOT NULL;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS growth_icon text;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS growth_label text;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS icon_name text DEFAULT 'Shield'::text NOT NULL;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS min_orders integer DEFAULT 0 NOT NULL;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS min_rating numeric DEFAULT 0 NOT NULL;
ALTER TABLE public.trust_tier_config ADD COLUMN IF NOT EXISTS tier_label text;
ALTER TABLE public.user_notifications ADD COLUMN IF NOT EXISTS payload jsonb;
ALTER TABLE public.user_notifications ADD COLUMN IF NOT EXISTS queue_item_id uuid;
ALTER TABLE public.user_notifications ADD COLUMN IF NOT EXISTS reference_id text;
ALTER TABLE public.user_notifications ADD COLUMN IF NOT EXISTS reference_path text;
ALTER TABLE public.visitor_entries ADD COLUMN IF NOT EXISTS parking_slot_id uuid;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS accepted_at timestamp with time zone;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS accepted_by uuid;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS duration_hours integer DEFAULT 1;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval);
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS location_details text;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS payment_amount numeric(10,2);
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'pending'::text;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS price numeric(10,2);
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS resident_id uuid;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS resident_rating integer;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS resident_review text;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS start_time timestamp with time zone;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS target_society_ids text[];
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS urgency text DEFAULT 'normal'::text;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS visibility_scope text DEFAULT 'society'::text NOT NULL;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS voice_summary_url text;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS worker_rating integer;
ALTER TABLE public.worker_job_requests ADD COLUMN IF NOT EXISTS worker_review text;