ALTER TABLE public.order_otp_codes ADD COLUMN IF NOT EXISTS otp_hash text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_confirmed_by_seller boolean;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_screenshot_url text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS upi_transaction_ref text;
ALTER TABLE public.seller_profiles ADD COLUMN IF NOT EXISTS default_action_type text;
ALTER TABLE public.seller_profiles ADD COLUMN IF NOT EXISTS low_stock_alert_threshold integer DEFAULT 3;
ALTER TABLE public.seller_profiles ADD COLUMN IF NOT EXISTS on_time_delivery_pct numeric;
ALTER TABLE public.seller_profiles ADD COLUMN IF NOT EXISTS store_location_label text;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS delivery_fee_share numeric DEFAULT 0 NOT NULL;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS eligible_at timestamp with time zone;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS hold_reason text;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS order_id uuid;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS razorpay_transfer_id text;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS settlement_status text DEFAULT 'pending'::text NOT NULL;
ALTER TABLE public.seller_settlements ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE public.service_bookings ADD COLUMN IF NOT EXISTS cancellation_reason text;
ALTER TABLE public.service_bookings ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone;
ALTER TABLE public.service_bookings ADD COLUMN IF NOT EXISTS reminder_1h_sent_at timestamp with time zone;
ALTER TABLE public.service_bookings ADD COLUMN IF NOT EXISTS reminder_24h_sent_at timestamp with time zone;
ALTER TABLE public.service_bookings ADD COLUMN IF NOT EXISTS rescheduled_from uuid;
ALTER TABLE public.service_bookings ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.session_feedback ADD COLUMN IF NOT EXISTS booking_id uuid;
ALTER TABLE public.session_feedback ADD COLUMN IF NOT EXISTS buyer_id uuid;
ALTER TABLE public.skill_listings ADD COLUMN IF NOT EXISTS availability text;
ALTER TABLE public.skill_listings ADD COLUMN IF NOT EXISTS skill_name text;