CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_ai_review_log_target ON public.ai_review_log USING btree (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON public.audit_log USING btree (actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_society_created ON public.audit_log USING btree (society_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bulletin_comments_post ON public.bulletin_comments USING btree (post_id);
CREATE INDEX IF NOT EXISTS idx_bulletin_posts_created ON public.bulletin_posts USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bulletin_posts_society ON public.bulletin_posts USING btree (society_id);
CREATE INDEX IF NOT EXISTS idx_bulletin_rsvps_post ON public.bulletin_rsvps USING btree (post_id);
CREATE INDEX IF NOT EXISTS idx_bulletin_votes_post ON public.bulletin_votes USING btree (post_id);
CREATE INDEX IF NOT EXISTS idx_call_feedback_interaction ON public.call_feedback USING btree (interaction_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user_product ON public.cart_items USING btree (user_id, product_id);
CREATE INDEX IF NOT EXISTS idx_category_config_requires_license ON public.category_config USING btree (requires_license) WHERE (requires_license = true);
CREATE INDEX IF NOT EXISTS idx_construction_milestones_society ON public.construction_milestones USING btree (society_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_csf_starts_live_activity ON public.category_status_flows USING btree (starts_live_activity) WHERE (starts_live_activity = true);
CREATE INDEX IF NOT EXISTS idx_cst_lookup ON public.category_status_transitions USING btree (parent_group, transaction_type, from_status);
CREATE INDEX IF NOT EXISTS idx_delivery_addresses_user ON public.delivery_addresses USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_society ON public.delivery_assignments USING btree (society_id);
CREATE INDEX IF NOT EXISTS idx_delivery_feedback_order_id ON public.delivery_feedback USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_delivery_feedback_seller_id ON public.delivery_feedback USING btree (seller_id);
CREATE INDEX IF NOT EXISTS idx_delivery_locations_assignment_id ON public.delivery_locations USING btree (assignment_id);
CREATE INDEX IF NOT EXISTS idx_delivery_locations_recorded_at ON public.delivery_locations USING btree (recorded_at);
CREATE INDEX IF NOT EXISTS idx_dispute_tickets_society_created ON public.dispute_tickets USING btree (society_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dispute_tickets_society_status ON public.dispute_tickets USING btree (society_id, status);
CREATE INDEX IF NOT EXISTS idx_featured_items_target_societies ON public.featured_items USING gin (target_society_ids);
CREATE INDEX IF NOT EXISTS idx_flows_lookup ON public.category_status_flows USING btree (parent_group, transaction_type, sort_order);
CREATE INDEX IF NOT EXISTS idx_gate_entries_society_time ON public.gate_entries USING btree (society_id, entry_time DESC);
CREATE INDEX IF NOT EXISTS idx_help_requests_society ON public.help_requests USING btree (society_id);
CREATE INDEX IF NOT EXISTS idx_help_responses_request ON public.help_responses USING btree (request_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_dues_society_month ON public.maintenance_dues USING btree (society_id, month DESC);
CREATE INDEX IF NOT EXISTS idx_marketplace_events_type ON public.marketplace_events USING btree (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_queue_dedup ON public.notification_queue USING btree (reference_path, created_at DESC) WHERE (reference_path IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_notification_queue_retry ON public.notification_queue USING btree (status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_notification_queue_status ON public.notification_queue USING btree (status, created_at) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read_created ON public.user_notifications USING btree (user_id, is_read, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_booking_idempotency ON public.orders USING btree (buyer_id, idempotency_key) WHERE ((idempotency_key IS NOT NULL) AND (order_type = 'booking'::text));
CREATE INDEX IF NOT EXISTS idx_orders_buyer_created ON public.orders USING btree (buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_buyer_id ON public.orders USING btree (buyer_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_buyer_idempotency ON public.orders USING btree (buyer_id, idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_orders_buyer_status ON public.orders USING btree (buyer_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_buyer_status_created ON public.orders USING btree (buyer_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_seller_created ON public.orders USING btree (seller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_seller_id ON public.orders USING btree (seller_id);
CREATE INDEX IF NOT EXISTS idx_orders_seller_status ON public.orders USING btree (seller_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_phone_otp_phone_status ON public.phone_otp_verifications USING btree (phone_number, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_banner_lookup ON public.products USING btree (category, approval_status, is_available);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON public.products USING gin (name public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_search_vector ON public.products USING gin (search_vector);
CREATE INDEX IF NOT EXISTS idx_products_seller_avail ON public.products USING btree (seller_id, is_available, approval_status);
CREATE INDEX IF NOT EXISTS idx_products_seller_available_approved ON public.products USING btree (seller_id, is_available, approval_status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_email_unique ON public.profiles USING btree (email) WHERE ((email IS NOT NULL) AND (email <> ''::text));
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_phone_unique ON public.profiles USING btree (phone) WHERE ((phone IS NOT NULL) AND (phone <> ''::text));
CREATE INDEX IF NOT EXISTS idx_sc_buyer_seller ON public.seller_conversations USING btree (buyer_id, seller_id);
CREATE INDEX IF NOT EXISTS idx_sci_buyer_id ON public.seller_contact_interactions USING btree (buyer_id);
CREATE INDEX IF NOT EXISTS idx_sci_seller_id ON public.seller_contact_interactions USING btree (seller_id);
CREATE INDEX IF NOT EXISTS idx_scm_conversation ON public.seller_conversation_messages USING btree (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_seller_coords ON public.seller_profiles USING btree (latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_seller_profiles_banner_lookup ON public.seller_profiles USING btree (society_id, is_available, verification_status);
CREATE INDEX IF NOT EXISTS idx_service_bookings_buyer ON public.service_bookings USING btree (buyer_id);
CREATE INDEX IF NOT EXISTS idx_service_bookings_buyer_slot ON public.service_bookings USING btree (buyer_id, slot_id) WHERE (status <> ALL (ARRAY['cancelled'::text, 'no_show'::text]));
CREATE INDEX IF NOT EXISTS idx_service_bookings_date_status ON public.service_bookings USING btree (booking_date, status);
CREATE INDEX IF NOT EXISTS idx_service_bookings_seller ON public.service_bookings USING btree (seller_id);
CREATE INDEX IF NOT EXISTS idx_service_bookings_slot ON public.service_bookings USING btree (slot_id);
CREATE INDEX IF NOT EXISTS idx_service_slots_product_date ON public.service_slots USING btree (product_id, slot_date);
CREATE INDEX IF NOT EXISTS idx_service_slots_seller_date ON public.service_slots USING btree (seller_id, slot_date);
CREATE INDEX IF NOT EXISTS idx_skill_endorsements_skill ON public.skill_endorsements USING btree (skill_id);
CREATE INDEX IF NOT EXISTS idx_skill_listings_society ON public.skill_listings USING btree (society_id);
CREATE INDEX IF NOT EXISTS idx_slot_holds_expires ON public.slot_holds USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_snag_tickets_society_status ON public.snag_tickets USING btree (society_id, status);
CREATE INDEX IF NOT EXISTS idx_societies_norm_trgm ON public.societies USING gin (normalized_name public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_society_activity_society_created ON public.society_activity USING btree (society_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_society_expenses_society_created ON public.society_expenses USING btree (society_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_buyer ON public.subscriptions USING btree (buyer_id);
CREATE INDEX IF NOT EXISTS idx_trigger_errors_created_at ON public.trigger_errors USING btree (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_buyer_slot_active ON public.service_bookings USING btree (buyer_id, slot_id) WHERE (status <> ALL (ARRAY['cancelled'::text, 'no_show'::text]));
CREATE INDEX IF NOT EXISTS idx_user_notifications_dedup ON public.user_notifications USING btree (user_id, type, reference_path, created_at DESC) WHERE (reference_path IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_notifications_queue_item ON public.user_notifications USING btree (queue_item_id) WHERE (queue_item_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_user_notifications_user_read ON public.user_notifications USING btree (user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_role ON public.user_roles USING btree (user_id, role);
CREATE INDEX IF NOT EXISTS idx_visitor_entries_society_status ON public.visitor_entries USING btree (society_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_proximity_notif_per_order ON public.user_notifications USING btree (user_id, reference_path) WHERE (type = 'delivery_proximity'::text);
CREATE UNIQUE INDEX IF NOT EXISTS uq_service_availability_seller_day_null_product ON public.service_availability_schedules USING btree (seller_id, day_of_week) WHERE (product_id IS NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_service_availability_seller_product_day_notnull ON public.service_availability_schedules USING btree (seller_id, product_id, day_of_week) WHERE (product_id IS NOT NULL);